# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Feedback Mechanisms
tagline:             ''
description:         ''
url:                 'http://feedbackmechanisms.org'
baseurl:             'http://feedbackmechanisms.org'
paginate:            5
paginate_path:       "/blog/page:num/"

# About/contact


# Custom vars
version:             1.0.0
